Repository oharastream/ohara, pull requests merged in 2020-08, with the labels that each got.

#5541 #5434 Remove jdbc prefix of variable name for the jdbc source connector
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceConnector.scala
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceConnectorConfig.scala
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceTask.scala
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/package.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorConfig.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorDefinition.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorRecovery.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTask.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskOffset.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4Oracle.scala
Labels: connector, it, v0.12.0

#5542 #5434 Modify variable name and remove unused setting for the jdbc source connector
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceConnector.scala
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceConnectorConfig.scala
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/package.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnector.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorConfig.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorDataType.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorDefinition.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorExactlyOnce.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorRecovery.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorTimeRange.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTask.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskOffset.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestMultipleJDBCSourceConnector.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4Oracle.scala
Labels: connector, it, v0.12.0

#5548 #5547 an new dockerfile used to build kafka with specify revision
  docker/custom_broker.dockerfile
Labels: others, v0.12.0

#5550 #5549 Enable to configure the repo in building custom broker image
  docker/custom_broker.dockerfile
Labels: others, v0.12.0

#5545 #5417 [Manager] Use enum instead of literal string for topic state
  ohara-manager/client/cypress/api/connectorApi.test.ts
  ohara-manager/client/cypress/api/topicApi.test.ts
  ohara-manager/client/cypress/support/customCommands.ts
  ohara-manager/client/src/api/apiInterface/topicInterface.ts
  ohara-manager/client/src/components/Node/ClusterStateChip.js
  ohara-manager/client/src/components/Topic/TopicTable.js
  ohara-manager/client/src/hooks/topicHooks.js
  ohara-manager/client/src/observables/topics.ts
  ohara-manager/client/src/store/epics/topic/startTopicEpic.js
Labels: manager, v0.12.0

#5553 #5552 Update kafka from 2.5.0 to 2.6.0
  docker/broker.dockerfile
  docker/configurator.dockerfile
  docker/worker.dockerfile
  gradle/dependencies.gradle
  ohara-stream/src/main/java/oharastream/ohara/stream/ostream/OStreamImpl.java
Labels: others, stream, v0.12.0

#5555 #5554 Update zookeeper from 3.5.7 to 3.5.8
  docker/zookeeper.dockerfile
Labels: others, v0.12.0

#5557 #5556 Enable to build worker image with up-to-date kafka source code
  build.gradle
  docker/custom_worker.dockerfile
Labels: others, v0.12.0

#5559 #5558 The file name of storing worker version should be worker_versio…
  docker/custom_worker.dockerfile
  docker/worker.dockerfile
Labels: others, v0.12.0

#5562 #5561 Upgrade gradle from 6.5.1 to 6.6
  docker/deps.dockerfile
  gradle/wrapper/gradle-wrapper.properties
Labels: others, v0.12.0

#5566 #5564 Failed to locate the assembly file in custom image
  docker/custom_broker.dockerfile
  docker/custom_worker.dockerfile
Labels: others, v0.12.0

#5568 #5567 Remove useless Serializable interface from CounterMBean
  ohara-metrics/src/main/java/oharastream/ohara/metrics/basic/Counter.java
Labels: metrics, v0.12.0

#5569 #5565 Remove the gradle installation from deps image
  docker/deps.dockerfile
Labels: others, v0.12.0

#5571 #5570 Replace deprecated ConcMarkSweepGC by G1GC
  bin/ohara-env.sh
Labels: others, v0.12.0

#5578 #5577 Use gradle application plugin to replace our custom script in o…
  ohara-configurator/build.gradle
Labels: configurator, v0.12.0

#5574 #5573 Perf source should reuse existent data to reduce memory usage
  ohara-connector/src/main/scala/oharastream/ohara/connector/perf/PerfSourceTask.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/perf/TestPerfSourceTask.scala
  ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/RowSourceTask.java
Labels: connector, kafka, v0.12.0

#5580 #5579 Support "queued.max.request.bytes" and "socket.request.max.bytes" to …
  ohara-agent/src/main/scala/oharastream/ohara/agent/ArgumentsBuilder.scala
  ohara-agent/src/main/scala/oharastream/ohara/agent/BrokerCollie.scala
  ohara-client/src/main/scala/oharastream/ohara/client/configurator/BrokerApi.scala
  ohara-configurator/src/test/scala/oharastream/ohara/configurator/route/TestBrokerRoute.scala
Labels: agent, client, configurator, v0.12.0

#5576 #5575 RowSourceTask#commitRecord should apply lazy field initialization
  ohara-kafka/src/main/java/oharastream/ohara/kafka/RecordMetadata.java
  ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/RowSourceRecord.java
  ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/RowSourceTask.java
  ohara-kafka/src/test/java/oharastream/ohara/kafka/TestRecordMetadata.java
  ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/TestRowSourceRecord.java
Labels: kafka, v0.12.0

#5582 #5581 Enable users to configure the compression type used by source c…
  ohara-agent/src/main/scala/oharastream/ohara/agent/WorkerCollie.scala
  ohara-client/src/main/scala/oharastream/ohara/client/configurator/WorkerApi.scala
  ohara-client/src/test/scala/oharastream/ohara/client/configurator/TestWorkerApi.scala
  ohara-configurator/src/test/scala/oharastream/ohara/configurator/route/TestWorkerRoute.scala
Labels: agent, client, configurator, v0.12.0

#5585 #5584 Remove older document link for the README.md file
  README.md
Labels: others, v0.12.0

#5586 #5551 Volume API supports padding missing from path
  ohara-agent/src/main/scala/oharastream/ohara/agent/RemoteFolderHandler.scala
Labels: agent, v0.12.0

#5589 #5588 Support compacted topic - "cleanup.policy" and "min.cleanable.dirty.ratio"
  ohara-client/src/main/scala/oharastream/ohara/client/configurator/TopicApi.scala
  ohara-configurator/src/test/scala/oharastream/ohara/configurator/route/TestTopicRoute.scala
Labels: client, configurator, v0.12.0

#5591 #5590 Refactor StreamUtils#zipWithIndex to avoid unnecessary conversion
  ohara-common/src/main/java/oharastream/ohara/common/util/StreamUtils.java
  ohara-common/src/test/java/oharastream/ohara/common/util/TestStreamUtils.java
  ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/csv/sink/TestTopicPartitionWriter.java
Labels: common, kafka, v0.12.0

#5546 #5434 Avoid using while loop to calculate time range
  ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceTask.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorExactlyOnce.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorRecovery.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorTimeRange.scala
  ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTask.scala
Labels: connector, v0.12.0

#5593 #5592 Upgrade gradle from 6.6 to 6.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: others, v0.12.0

#5595 #5594 Exclude env-required ITs from ohara-it test task
  build.gradle
  ohara-it/src/test/scala/oharastream/ohara/it/ContainerPlatform.scala
  ohara-it/src/test/scala/oharastream/ohara/it/WithRemoteConfigurator.scala
  ohara-it/src/test/scala/oharastream/ohara/it/collie/TestContainerClient.scala
  ohara-it/src/test/scala/oharastream/ohara/it/collie/TestMountVolume.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/TestSmbFileSystem.scala
  ohara-it/src/test/scala/oharastream/ohara/it/script/TestVersionFile.scala
Labels: it, others, v0.12.0

#5599 #5598 Reset excludeCategories for custom IT tasks
  build.gradle
Labels: others, v0.12.0

#5597 #5596 Remove o.o.i.c.s.ITSmbProps and package object
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/ITSmbProps.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/SmbEnv.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/TestSmbFileSystem.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/TestSmbSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/TestSmbSource.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/smb/package.scala
Labels: it, v0.12.0

#5601 #5600 Move the catalog to parent class
  ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/BasicTestConnectorCollie.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestOracleJDBCSourceConnector.scala
  ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestPostgresqlJDBCSourceConnector.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Ftp.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Jdbc.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Samba.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSource.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSourceToHDFSSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4HdfsSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4Oracle.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4PerfSource.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSink.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSource.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/WithPerformanceRemoteConfigurator.scala
  ohara-it/src/test/scala/oharastream/ohara/it/performance/WithPerformanceRemoteWorkers.scala
Labels: it, v0.12.0
